version: '3.8'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: testing_portal_web
    depends_on:
      - db
      - redis
    environment:
      PHP_LOGS_PATH: /var/log/apache2/php.log
      SMTP_HOST: <DEFINE SMTP HOST>
      SMTP_PORT: 465
      SMTP_USER: <DEFINE SMTP USER>
      SMTP_PASSWORD: <DEFINE SMTP PASSWORD>
      DOMAIN_FOR_CONFIRMATION: <DEFINE DOMAIN FOR YOU SITE, IF RUNNING ON LOCALHOST - http://localhost:8000>
      DB_HOST: testing_portal_db
      DB_PORT: 3306
      DB_NAME: testing_portal_db
      DB_USER: root
      DB_PASSWORD: <DEFINE DB PASSWORD>
    volumes:
      - ./:/var/www/html
    ports:
      - "8000:80"

  db:
    image: mysql:8.1.0
    container_name: testing_portal_db
    environment:
      MYSQL_DATABASE: testing_portal_db
      MYSQL_ROOT_PASSWORD: <DEFINE DB PASSWORD>
    volumes:
      - ./init_db:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin:5.2.1
    container_name: phpmyadmin
    depends_on:
      - db
    links:
      - db
    environment:
      PMA_HOST: db
    ports:
      - "9000:80"
  
  redis:
    image: redis/redis-stack:7.2.0-v6
    container_name: redis
    ports:
      - "9001:8001"
